FROM continuumio/miniconda3:4.9.2 

# Modified from staphb/vadr
# https://hub.docker.com/r/staphb/vadr/dockerfile

# metadata - optional, but highly recommended
LABEL base.image="continuumio/miniconda3:4.8.2"
LABEL dockerfile.version="1"
LABEL software="VADR and a converter script for DDBJ"
LABEL software.version=${VADR_VERSION}
LABEL description="This software does viral annotations"
LABEL website="https://github.com/ncbi/vadr"
LABEL license="https://github.com/ncbi/vadr/blob/master/LICENSE"
LABEL maintainer1="Anders Goncalves da Silva"
LABEL maintainer2="Curtis Kapsak"
LABEL maintainer3="Yasuhiro Tanizawa"


ENV VADR_VERSION="1.2"\
  VADR_CORONA_MODELS_VERSION="1.2-2" \
  LC_ALL=C \
  VADRINSTALLDIR=/opt/vadr

ENV VADRSCRIPTSDIR=$VADRINSTALLDIR/vadr \
 VADRMODELDIR=$VADRINSTALLDIR/vadr-models-sarscov2-${VADR_CORONA_MODELS_VERSION} \
 VADRINFERNALDIR=$VADRINSTALLDIR/infernal/binaries \
 VADREASELDIR=$VADRINSTALLDIR/infernal/binaries \
 VADRHMMERDIR=$VADRINSTALLDIR/hmmer/binaries \
 VADRBIOEASELDIR=$VADRINSTALLDIR/Bio-Easel \
 VADRSEQUIPDIR=$VADRINSTALLDIR/sequip \
 VADRFASTADIR=$VADRINSTALLDIR/fasta/bin \
 VADRBLASTDIR=$VADRINSTALLDIR/ncbi-blast/bin

ENV PERL5LIB=$VADRSCRIPTSDIR:$VADRSEQUIPDIR:$VADRBIOEASELDIR/blib/lib:$VADRBIOEASELDIR/blib/arch:$PERL5LIB \
PATH=$VADRSCRIPTSDIR:$VADRBLASTDIR:$PATH

RUN  conda install -y -c biobuilds perl=5.22 
RUN  conda install -y curl unzip autoconf automake make 
RUN  conda install -y -c bioconda  perl-inline-c perl-lwp-simple 
RUN conda install -c conda-forge -y cxx-compiler




RUN conda install -y bash
RUN mkdir -p ${VADRINSTALLDIR} && \
  cd ${VADRINSTALLDIR} && \
  wget https://raw.githubusercontent.com/ncbi/vadr/release-${VADR_VERSION}/vadr-install.sh && \
  cd ${VADRINSTALLDIR} && \
  bash vadr-install.sh linux


RUN cd ${VADRINSTALLDIR} && \
 wget https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/sarscov2/${VADR_CORONA_MODELS_VERSION}/vadr-models-sarscov2-${VADR_CORONA_MODELS_VERSION}.tar.gz && \
 tar -xf vadr-models-sarscov2-${VADR_CORONA_MODELS_VERSION}.tar.gz && \
 rm -f vadr-models-sarscov2-${VADR_CORONA_MODELS_VERSION}.tar.gz


RUN echo "export LS_OPTIONS='--color=auto'" >> /root/.bashrc && \
  echo "alias ls='ls $LS_OPTIONS" >> /root/.bashrc && \
  echo "alias ll='ls $LS_OPTIONS -l'" >> /root/.bashrc && \
  echo "alias la='ls $LS_OPTIONS -al'" >> /root/.bashrc && \
  eval "`dircolors`"

RUN conda install -y -c bioconda mafft=7.475 snpeff=5.0 biopython=1.78
RUN conda install -y git
ARG UPDATE_ME_TO_DISABLE_CACHE_BELOW_THIS_LINE=1
RUN cd / && \
  git clone https://github.com/nigyta/dfast_vrl.git && \
  cd /usr/bin && \
  ln -s /dfast_vrl/dfast_vrl 


# set working directory
WORKDIR /data

RUN bash 


