# This docker-compose file is only for development use
version: '3.7'
services:

    app:
        image: nigyta/dfast_vrl:1.3-0.1
        command: tail -f /dev/null
        volumes:
            - .:/dfast_vrl
            - ..:/data
        environment:
            - TZ=Asia/Tokyo            
