# This docker-compose file is only for development use
version: '3.7'
services:

    app:
        image: nigyta/dfast_vrl:latest
        build:
            context: .
        command: tail -f /dev/null
        volumes:
            - .:/dfast_vrl
            - ../test_data:/data
        environment:
            - TZ=Asia/Tokyo            
