# This docker-compose file is only for development use
version: '3.7'
services:

    app:
        # image: nigyta/dfast_vrl:latest
        image: nigyta/dfast_vrl:1.6.4-0.6
        build:
            context: .
        command: tail -f /dev/null
        volumes:
            - .:/dfast_vrl
            - ./dev:/data
            - ../vadr_models:/vadr_models
        environment:
            - TZ=Asia/Tokyo            
            - VADRMODELDIR=/vadr_models