
dict_product = {
    "A32.5L": "A32.5L protein",
    "M137R": "M137R protein",
    "MPXVgp154": "hypothetical protein",
    "A5L protein-like": "A5L-like protein",
    "Brix domain protein": "Brix domain-containing protein",
    "DUF1029 domain protein": "DUF1029 domain-containing protein",
    "EGF-like domain protein": "EGF-like domain-containing protein",
    "NUDIX domain protein": "NUDIX domain-containing protein",
    "Profilin domain protein": "profilin domain-containing protein",
    "RNA polymerase-associate": "RNA polymerase-associate protein",
    "Crescent membrane and immature virion formatio": "crescent membrane and immature virion formation protein",
    "MPXVgp007": "D4L protein",
    "MPXVgp021": "D18L protein",
    "MPV-Z-N2R": "MPV-Z-N2R protein",
    "A-type inclusion protein (Cop-A25L); A26L": "A-type inclusion protein",
    "A-type inclusion protein (Cop-A25L); A27L": "A-type inclusion protein",
    "BTB Kelch-domain containing protein CRL complex (Cop-A55R); B1R kelch-like": "BTB Kelch-domain containing protein CRL complex",
    "Host range protein; D2L": "host range protein",
    "IL-1 beta inhibitor (Cop-B17L); B15L": "IL-1 beta inhibitor",
    "NMDA receptor-like protein; R1R": "NMDA receptor-like protein",
    "kelch-like protein (EV-M-167); B18R kelch-like fragment": "kelch-like protein",

    # Added 2024-11-22
    # 1) 間違い修正
    "Cap-specific mRNA": "Cap-specific mRNA (nucleoside-2'-O-)-methyltransferase",
    "Orthopoxvirus A26L/A30L protein": "39 kDa core protein",
    
    # 2) 大文字修正と書式統一
    "Iev morphogenesis protein": "IEV morphogenesis protein",
    "Ser/thr kinase": "Ser/Thr protein kinase",
    "Tyr/ser protein phosphatase": "Tyr/Ser protein phosphatase",
    "Serine/threonine-protein kinase": "Ser/Thr protein kinase",
    
    # 3) 先頭文字を小文字に
    "Ankyrin repeat protein (14)": "ankyrin repeat protein (14)",
    "Ankyrin repeat protein (2)": "ankyrin repeat protein (2)",
    "Ankyrin repeat protein (25)": "ankyrin repeat protein (25)",
    "Ankyrin repeat protein (39)": "ankyrin repeat protein (39)",
    "Ankyrin repeat protein (44)": "ankyrin repeat protein (44)",
    "Ankyrin-like protein (1)": "ankyrin-like protein (1)",
    "Ankyrin-like protein (3)": "ankyrin-like protein (3)",
    "Ankyrin-like protein (46)": "ankyrin-like protein (46)",
    "Assembly protein G7": "assembly protein G7",
    "Carbonic anhydrase": "carbonic anhydrase",
    "Caspase-9 inhibitor": "caspase-9 inhibitor",
    "Chemokine binding protein": "chemokine binding protein",
    "Copper/zinc superoxide dismutase": "copper/zinc superoxide dismutase",
    "Core protein A15": "core protein A15",
    "Crescent membrane and immature virion formation protein": "crescent membrane and immature virion formation protein",
    "Cytochrome C oxidase": "cytochrome C oxidase",
    "Cytoplasmic protein": "cytoplasmic protein",
    "Double-stranded RNA binding protein": "double-stranded RNA binding protein",
    "Early transcription factor 70 kDa subunit": "early transcription factor 70 kDa subunit",
    "Early transcription factor 82 kDa subunit": "early transcription factor 82 kDa subunit",
    "Entry-fusion complex essential component": "entry-fusion complex essential component",
    "Entry/fusion complex component": "entry/fusion complex component",
    "Envelope protein A28 homolog": "envelope protein A28 homolog",
    "Glutaredoxin-1": "glutaredoxin-1",
    "Glutaredoxin-2": "glutaredoxin-2",
    "Hemagglutinin": "hemagglutinin",
    "Holliday junction resolvase": "holliday junction resolvase",
    "Host range protein": "host range protein",
    "Hydroxysteroid dehydrogenase": "hydroxysteroid dehydrogenase",
    "Interleukin-18-binding protein": "interleukin-18-binding protein",
    "Intermediate transcription factor VITF-3 (1)": "intermediate transcription factor VITF-3 (1)",
    "Intermediate transcription factor VITF-3 (2)": "intermediate transcription factor VITF-3 (2)",
    "Internal virion L3/FP4 protein": "internal virion L3/FP4 protein",
    "Intracellular viral protein": "intracellular viral protein",
    "Late protein H7": "late protein H7",
    "Late transcription elongation factor": "late transcription elongation factor",
    "Late transcription factor VLTF-1": "late transcription factor VLTF-1",
    "Late transcription factor VLTF-2 (2)": "late transcription factor VLTF-2 (2)",
    "Late transcription factor VLTF-3 (1)": "late transcription factor VLTF-3 (1)",
    "Late transcription factor VLTF-4 (1)": "late transcription factor VLTF-4 (1)",
    "Membrane protein CL5": "membrane protein CL5",
    "Membrane protein E8": "membrane protein E8",
    "Metalloendopeptidase": "metalloendopeptidase",
    "Myristoylated protein E7": "myristoylated protein E7",
    "Myristylated protein": "myristylated protein",
    "Nucleic acid binding protein VP8/L4R": "nucleic acid binding protein VP8/L4R",
    "Nucleoside triphosphatase I": "nucleoside triphosphatase I",
    "Palmytilated EEV membrane protein": "palmytilated EEV membrane protein",
    "Phospholipase-D-like protein": "phospholipase-D-like protein",
    "Poly(A) polymerase catalytic subunit (3)": "poly(A) polymerase catalytic subunit (3)",
    "Profilin domain-containing protein": "profilin domain-containing protein",
    "Protein F11": "protein F11",
    "Protein F14 (1)": "protein F14 (1)",
    "Protein F15": "protein F15",
    "Protein F16 (1)": "protein F16 (1)",
    "Putative monoglyceride lipase": "putative monoglyceride lipase",
    "Ribonucleoside-diphosphate reductase (2)": "ribonucleoside-diphosphate reductase (2)",
    "Ribonucleotide reductase small subunit": "ribonucleotide reductase small subunit",
    "Rifampicin resistance protein": "rifampicin resistance protein",
    "Schlafen (1)": "schlafen (1)",
    "Serpin": "serpin",
    "Soluble interferon-gamma receptor-like protein": "soluble interferon-gamma receptor-like protein",
    "Sulfhydryl oxidase": "sulfhydryl oxidase",
    "Telomere-binding protein": "telomere-binding protein",
    "Telomere-binding protein I1": "telomere-binding protein I1",
    "Telomere-binding protein I6 (1)": "telomere-binding protein I6 (1)",
    "Thymidine kinase": "thymidine kinase",
    "Thymidylate kinase": "thymidylate kinase",
    "Type-I membrane glycoprotein": "type-I membrane glycoprotein",
    "Uracil DNA glycosylase superfamily": "uracil DNA glycosylase superfamily",
    "Viral core cysteine proteinase": "viral core cysteine proteinase",
    "Viral membrane formation protein": "viral membrane formation protein",
    "Virion core protein D3": "virion core protein D3",
    "Virion core protein E11": "virion core protein E11",
    "Virion core protein P4a": "virion core protein P4a",
    "Virion core protein P4b": "virion core protein P4b",
    "Virion morphogenesis protein": "virion morphogenesis protein",
    "Virion protein D2": "virion protein D2",
    "Virulence protein": "virulence protein",
    "Zinc finger-like protein (1)": "zinc finger-like protein (1)",
    "Zinc finger-like protein (2)": "zinc finger-like protein (2)"

}

def fix_product_for_mpox(original_product):
    if original_product in dict_product:
        return dict_product[original_product]
    else:
        return original_product
